#!/bin/bash
# book - Open a book based on a search pattern

query=""
books_dir="$HOME/documents/books/"
n_match=""
tmp_file=""

open {
	(mupdf "$1")
}

usage {
	echo "Usage: book [Pattern]"
}

# Let the user interactivaly choose a book
inter_choice {
	i=0
	while read book; do
		printf "$i\t" && basename "$book"
		((i+=1))
	done < $tmp_file
	
	read -p "> " choice
	if [ $choice == "q" ] ; then
		return
	fi

	((choice+=1))	
	open "$(head -n $choice "$tmp_file" | tail -n 1)"
}

if [[ $# -eq 1 ]] ; then
	query=$1
	tmp_file="$(mktemp)"
	trap "rm $tmp_file" SIGINT SIGTERM
	find $books_dir -type f | grep -Ei "($1)" > $tmp_file
	n_match=$(wc -l < $tmp_file)
	
	if [[ $n_match -eq 0 ]] ; then
		echo "No match"
	elif [[ $n_match -eq 1 ]] ; then
		open "$(cat $tmp_file)"
	else
		inter_choice
	fi
else
	usage
fi 

